// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-p8kTOFpp4XoqKCXvwgvpKzZO7dN10Q',
    appId: '1:1027460266945:web:e0ca0d56c64d8ce0a44d40',
    messagingSenderId: '1027460266945',
    projectId: 'gestion-fournisseur-e5162',
    authDomain: 'gestion-fournisseur-e5162.firebaseapp.com',
    storageBucket: 'gestion-fournisseur-e5162.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_p0khRE1JOMjxqhP7AgRaHhvOfTVLWM',
    appId: '1:1027460266945:android:9f18e7502c1db52ca44d40',
    messagingSenderId: '1027460266945',
    projectId: 'gestion-fournisseur-e5162',
    storageBucket: 'gestion-fournisseur-e5162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_JReVQwtn4RI3j9T8Cn6SnJyHLbi6wNA',
    appId: '1:1027460266945:ios:48071927e4fe7cdba44d40',
    messagingSenderId: '1027460266945',
    projectId: 'gestion-fournisseur-e5162',
    storageBucket: 'gestion-fournisseur-e5162.appspot.com',
    iosBundleId: 'com.example.gestionFournisseur',
  );
}
